# Generated by Django 5.1.4 on 2025-08-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageImage',
            new_name='banner_image',
        ),
    ]
