# Generated by Django 5.2.9 on 2025-12-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default='Home', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(default='vallikavu', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(default=9207773847, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='kerala', max_length=100),
            preserve_default=False,
        ),
    ]
