# Generated by Django 5.2.9 on 2025-12-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_address_label_alter_address_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
