# Generated by Django 5.1.4 on 2025-09-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cosmetics_saloon'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='google_map_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='saloon',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/'),
        ),
    ]
