# Generated by Django 5.2.5 on 2025-10-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosmetics',
            options={'verbose_name': 'Cosmetic', 'verbose_name_plural': 'Cosmetics'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'verbose_name': 'Food Menu', 'verbose_name_plural': 'Food Menu'},
        ),
        migrations.AlterModelOptions(
            name='saloon',
            options={'verbose_name': 'Saloon', 'verbose_name_plural': 'Saloon'},
        ),
    ]
