# Generated by Django 5.2.5 on 2025-10-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cosmetics_options_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannervideo',
            name='video',
        ),
        migrations.AddField(
            model_name='bannervideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_image/'),
        ),
    ]
