# Generated by Django 5.2.5 on 2025-10-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_bannervideo_video_bannervideo_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerVideo',
            new_name='BannerImage',
        ),
    ]
